# Generated by Django 5.2.14 on 2026-05-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
