# Generated by Django 5.2.14 on 2026-05-18 11:59

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_chainkeyword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(django.db.models.functions.text.Upper('state'), name='idx_hospital_state_upper'),
        ),
    ]
