# Generated by Django 5.2.14 on 2026-05-21 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_hospital_idx_hospital_state_upper'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['phone_e164'], name='idx_hospital_phone'),
        ),
    ]
