# Generated by Django 5.2.14 on 2026-05-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling', '0002_seed_dummy_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='callattempt',
            name='recording_s3_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
