# Generated by Django 5.2.14 on 2026-05-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling', '0003_callattempt_recording_s3_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='callattempt',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='callschedule',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
