# Generated by Django 5.2.14 on 2026-05-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling', '0006_callattempt_voice_model'),
        ('hospital', '0008_hospital_idx_hospital_state_upper'),
        ('prompt', '0005_remove_prompt_objective_voice_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='callschedule',
            name='batch_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='callschedule',
            index=models.Index(fields=['batch_id'], name='idx_csched_batch_id'),
        ),
    ]
