# Generated by Django 5.2.14 on 2026-05-21 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling', '0007_callschedule_batch_id_and_more'),
        ('hospital', '0008_hospital_idx_hospital_state_upper'),
        ('prompt', '0005_remove_prompt_objective_voice_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'call_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallScheduleHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'call_schedule_hospital',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='callattempt',
            name='is_starred',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='callattempt',
            index=models.Index(fields=['is_starred', '-created_at'], name='idx_cattempt_starred_at'),
        ),
        migrations.AddField(
            model_name='callcomment',
            name='call_attempt',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='calling.callattempt'),
        ),
        migrations.AddField(
            model_name='callschedulehospital',
            name='call_attempt',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='calling.callattempt'),
        ),
        migrations.AddField(
            model_name='callschedulehospital',
            name='hospital',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.hospital'),
        ),
        migrations.AddField(
            model_name='callschedulehospital',
            name='schedule',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='calling.callschedule'),
        ),
        migrations.AddIndex(
            model_name='callcomment',
            index=models.Index(fields=['call_attempt', 'created_at'], name='idx_ccomment_attempt_at'),
        ),
        migrations.AddIndex(
            model_name='callschedulehospital',
            index=models.Index(fields=['schedule', 'order'], name='idx_csh_schedule_order'),
        ),
        migrations.AddConstraint(
            model_name='callschedulehospital',
            constraint=models.UniqueConstraint(fields=('schedule', 'order'), name='uq_csh_schedule_order'),
        ),
        # Drop the superseded batch mechanism (DRT-5293): the ordered
        # `CallScheduleHospital` targets replace `CallSchedule.batch_id`.
        migrations.RemoveIndex(
            model_name='callschedule',
            name='idx_csched_batch_id',
        ),
        migrations.RemoveField(
            model_name='callschedule',
            name='batch_id',
        ),
    ]
