# Generated by Django 5.2.14 on 2026-05-21 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calling', '0009_backfill_schedule_targets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callschedule',
            name='hospital',
        ),
    ]
