# Generated by Django 5.2.14 on 2026-05-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0002_seed_v2'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='prompt',
            name='uq_prompt_active_per_name',
        ),
        migrations.AddField(
            model_name='prompt',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='prompt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('name',), name='uq_prompt_active_per_name'),
        ),
    ]
