# Generated by Django 5.2.14 on 2026-05-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0003_remove_prompt_uq_prompt_active_per_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='prompt',
            name='uq_prompt_active_per_name',
        ),
        migrations.RemoveIndex(
            model_name='prompt',
            name='idx_prompt_obj_active',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='language',
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['name', '-version'], name='idx_prompt_name_ver'),
        ),
    ]
