# Generated by Django 5.2.14 on 2026-05-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=120)),
                ('eta', models.DateTimeField()),
                ('args', models.JSONField(default=list)),
                ('kwargs', models.JSONField(default=dict)),
                ('options', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scheduled_task',
                'indexes': [models.Index(fields=['eta', 'dispatched_at'], name='idx_schtask_eta_dispatched')],
            },
        ),
    ]
