# Generated by Django 5.2.14 on 2026-05-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcingjob',
            name='force_refresh',
        ),
        migrations.RemoveField(
            model_name='sourcingjob',
            name='refresh_after_days',
        ),
    ]
