# Generated by Django 5.2.14 on 2026-05-16 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0002_drop_refresh_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcingjob',
            name='estimated_cost_usd',
        ),
        migrations.RemoveField(
            model_name='sourcingjob',
            name='estimated_places_count',
        ),
        migrations.RemoveField(
            model_name='sourcingjob',
            name='is_dry_run',
        ),
    ]
