# Generated by Django 5.2.14 on 2026-05-16 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0003_drop_dry_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcingjob',
            name='last_place_id',
        ),
        migrations.RemoveField(
            model_name='sourcingjob',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sourcingjob',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='sourcingjob',
            name='page_cursor',
        ),
        migrations.RemoveField(
            model_name='sourcingjob',
            name='radius_km',
        ),
        migrations.AddField(
            model_name='sourcingjob',
            name='call_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sourcingjob',
            name='call_limit',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='sourcingjob',
            name='capped_tile_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sourcingjob',
            name='completed_tiles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sourcingjob',
            name='failed_tile_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sourcingjob',
            name='max_depth',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='sourcingjob',
            name='partial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sourcingjob',
            name='partial_reason',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='sourcingjob',
            name='root_east',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sourcingjob',
            name='root_north',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sourcingjob',
            name='root_south',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sourcingjob',
            name='root_west',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sourcingjob',
            name='total_tiles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SourcingTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('south', models.DecimalField(decimal_places=6, max_digits=9)),
                ('west', models.DecimalField(decimal_places=6, max_digits=9)),
                ('north', models.DecimalField(decimal_places=6, max_digits=9)),
                ('east', models.DecimalField(decimal_places=6, max_digits=9)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(default='PENDING', max_length=16)),
                ('page_cursor', models.TextField(blank=True, null=True)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveSmallIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('capped_at_min_size', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='sourcing.sourcingjob')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='sourcing.sourcingtile')),
            ],
            options={
                'db_table': 'sourcing_tile',
                'indexes': [models.Index(fields=['job', 'status'], name='idx_st_job_status')],
            },
        ),
    ]
