# Generated by Django 5.2.14 on 2026-05-17 00:55

import json
import os

from django.db import migrations, models


def load_cities(apps, schema_editor):
    """Preload `city` from `sourcing/data/us_cities.json` — 51 state keys
    (50 + DC), ~32.8k Census places/CDPs + New England towns. Idempotent:
    skips when `city` is already populated."""

    City = apps.get_model('sourcing', 'City')
    if City.objects.exists():
        return
    path = os.path.join(os.path.dirname(__file__), '..', 'data', 'us_cities.json')
    with open(path, encoding='utf-8') as cities_file:
        data = json.load(cities_file)
    City.objects.bulk_create(
        [
            City(state_code=state_code, name=name)
            for state_code, names in data.items()
            for name in names
        ],
        batch_size=2000,
    )


def unload_cities(apps, schema_editor):
    apps.get_model('sourcing', 'City').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0004_tile_pipeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'city',
                'ordering': ['state_code', 'name'],
                'constraints': [models.UniqueConstraint(fields=('state_code', 'name'), name='uq_city_state_name')],
            },
        ),
        migrations.RunPython(load_cities, unload_cities),
    ]
