# Generated by Django 5.2.14 on 2026-05-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0005_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcingjob',
            name='merged_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
